import sgMail from '@sendgrid/mail';
import { DigestSection } from './types';
import { format } from 'date-fns';

if (process.env.SENDGRID_API_KEY) {
  sgMail.setApiKey(process.env.SENDGRID_API_KEY);
}

// 🎨 Premium "Morning Brew" / "Axios" Style Template
function generateEmailHTML(sections: DigestSection[], date: string): string {
  const sectionsHTML = sections.map(section => `
      <div style="margin-bottom: 40px; border-top: 2px solid #000; padding-top: 20px;">
        <h2 style="font-family: 'Merriweather', serif; font-size: 20px; font-weight: 900; color: #000; text-transform: uppercase; letter-spacing: 1px; margin-bottom: 15px;">
          ${section.title}
        </h2>
        
        <!-- The AI Narrative -->
        <div style="font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 16px; line-height: 1.6; color: #333; margin-bottom: 20px;">
          ${formatNarrative(section.summary || '')}
        </div>

        <!-- Quick Links -->
        <div style="background: #f8f9fa; padding: 15px; border-radius: 8px;">
            <p style="font-family: 'Helvetica Neue', sans-serif; font-size: 12px; font-weight: bold; color: #888; text-transform: uppercase; margin: 0 0 10px 0;">
                DEEP DIVE
            </p>
            <ul style="list-style: none; padding: 0; margin: 0;">
                ${section.items.map(item => `
                    <li style="margin-bottom: 10px; padding-left: 0;">
                        <a href="${item.link}" style="color: #2563eb; text-decoration: none; font-weight: 600; font-family: 'Helvetica Neue', sans-serif; font-size: 15px;">
                            ${item.title}
                        </a>
                        <span style="color: #666; font-size: 13px; font-family: 'Helvetica Neue', sans-serif;">
                            — ${item.source}
                        </span>
                    </li>
                `).join('')}
            </ul>
        </div>
      </div>
    `).join('');

  return `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <link href="https://fonts.googleapis.com/css2?family=Merriweather:wght@300;400;700;900&display=swap" rel="stylesheet">
    </head>
    <body style="margin: 0; padding: 0; background-color: #f4f4f4; -webkit-font-smoothing: antialiased;">
      
      <!-- Container -->
      <table width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation">
        <tr>
          <td align="center" style="padding: 20px 0;">
            <table width="100%" border="0" cellpadding="0" cellspacing="0" role="presentation" style="max-width: 600px; background: #ffffff; border: 1px solid #e0e0e0;">
              
              <!-- Header -->
              <tr>
                <td style="padding: 40px 30px; border-bottom: 4px solid #000; text-align: center;">
                    <h1 style="font-family: 'Merriweather', serif; font-size: 32px; font-weight: 900; margin: 0; color: #000; letter-spacing: -1px;">
                        The Daily Brief
                    </h1>
                    <p style="font-family: 'Helvetica Neue', sans-serif; font-size: 14px; color: #666; margin: 10px 0 0 0; text-transform: uppercase; letter-spacing: 1px;">
                        ${date} • Prepared for You
                    </p>
                </td>
              </tr>

              <!-- Content -->
              <tr>
                <td style="padding: 30px;">
                    ${sectionsHTML}
                </td>
              </tr>

              <!-- Footer -->
              <tr>
                <td style="padding: 30px; background: #000; color: #fff; text-align: center;">
                    <p style="font-family: 'Helvetica Neue', sans-serif; font-size: 14px; margin: 0;">
                        Generated by Your Personal AI Chief of Staff
                    </p>
                    <p style="font-family: 'Helvetica Neue', sans-serif; font-size: 12px; color: #888; margin: 10px 0 0 0;">
                        <a href="https://your-domain.com" style="color: #fff; text-decoration: underline;">Manage Preferences</a>
                    </p>
                </td>
              </tr>

            </table>
          </td>
        </tr>
      </table>

    </body>
    </html>
  `;
}

// Convert "**Bold**" markdown to "<strong>Bold</strong>" HTML
function formatNarrative(text: string): string {
  let html = text
    .replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>') // Bold
    .replace(/\n\n/g, '</p><p>'); // Paragraphs

  return `<p>${html}</p>`;
}

export async function sendDigestEmail(to: string, sections: DigestSection[]): Promise<void> {
  const today = format(new Date(), 'EEEE, MMMM d, yyyy');

  // Use verified sender from env (User Complaint #4 fixed)
  const fromEmail = process.env.USER_EMAIL || to;

  const msg = {
    to,
    from: fromEmail,
    subject: `☕️ Your Daily Briefing - ${today}`,
    html: generateEmailHTML(sections, today),
  };

  try {
    await sgMail.send(msg);
    console.log(`Digest email sent to ${to}`);
  } catch (error: any) {
    console.error('Error sending email:', error);
    if (error.response) {
      console.error(error.response.body);
    }
    throw error;
  }
}
